CREATE DATABASE universite_test;
USE universite_test;
SHOW TABLES;
SELECT COUNT(*) FROM ETUDIANT;
SHOW VARIABLES LIKE 'secure_file_priv';
SELECT * 
INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/etudiants.csv'
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM ETUDIANT;

CREATE TABLE etudiant_csv LIKE ETUDIANT;
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/etudiants.csv'
INTO TABLE etudiant_csv
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n';
ALTER TABLE INSCRIPTION 
  ADD INDEX idx_date_inscr(date_inscription);
ALTER TABLE INSCRIPTION 
  DROP INDEX idx_date_inscr;
EXPLAIN
SELECT e.nom, COUNT(i.id)
FROM ETUDIANT e
JOIN INSCRIPTION i ON i.etudiant_id = e.id
GROUP BY e.id;
ANALYZE TABLE INSCRIPTION;
OPTIMIZE TABLE INSCRIPTION;